### PR TITLE
Launcher3: Introduce memory info in overview

### PR DESCRIPTION
**Pull request by PacMM79**
This is convenient for monitoring device status and many OEMs have their design for this. It's time to have our own one.

[PacMM79: Adapt to crdroid launcher. Update quickstep overview actions dimens.xml]

Change-Id: I890c86c798055b1964506d9a4df1cef386562160
Signed-off-by: LibXZR <i@xzr.moe>

### CODE REVIEW

**Comment by ShevT** [comment]
Looks nice. I think it's better to put the information above the buttons, because finger out of habit falls into the "memory info" area.

**Comment by PacMM79** [comment]
@ShevT I'll do some changes to check this.

**Comment by neobuddy89** [comment]
@ShevT @PacMM79 

We need toggle to turn this off as well

**Comment by PacMM79** [comment]
2 different views added: Above actions + Top view. (Just to check)
Landscape recents view reduced a lot to fit meminfo because we don't have a clean way to margin center with actual config.
Any help to add toggle, pl?

**Comment by neobuddy89** [comment]
added.

**Pull request closed without merging**
