### PR TITLE
Launcher3: Disable wallpaper scrolling and wallpaper zooming by default

### PR DESCRIPTION
**Pull request by hipexscape**

### CODE REVIEW

**Comment by shutter-cat** [comment]
https://github.com/VoltageOS/packages_apps_Launcher3/commit/d6048cf465c10cff507144a90431d8a9218c01b9 authorship?

**Comment by gwolf2u** [comment]
not that I don't approve regarding authorship, but is not a "major" commit
disabling or enabling something by default that is
anyway, this wasn't merged since not all devices have an issue with, reason I recommended internally (but will write here also), to have this set as an overlay with devices that have issues, set this off

**Comment by shutter-cat** [comment]
> not that I don't approve regarding authorship, but is not a "major" commit disabling or enabling something by default that is anyway, this wasn't merged since not all devices have an issue with, reason I recommended internally (but will write here also), to have this set as an overlay with devices that have issues, set this off

It's not major commit, but copypasting shamelessly(even my derp with } lol) is not what we all want to see in development and especially in such famous rom as crdroid.

**Comment by ossilator** [comment]
it's a trivial change which doesn't qualify for copyright, so the discussion about authorship is moot. it would be still in good style to give credit for the investigation or idea, and provide a backlink to the original commit - if it was actually copied (which isn't obvious at all, given that there is hardly another way to do that change; the whitespace change is in fact subtly different, and both are common artifacts).

**Comment by StudioKeys** [comment]
> it's a trivial change which doesn't qualify for copyright, so the discussion about authorship is moot. it would be still in good style to give credit for the investigation or idea, and provide a backlink to the original commit - if it was actually copied (which isn't obvious at all, given that there is hardly another way to do that change; the whitespace change is in fact subtly different, and both are common artifacts).

Since it's moot, let me ask you this one thing, what do you feel when one of your commits is copied out with no authorships, will you feel bad or keep quiet about it?

Again all commits made are done with proper testing and spending enormous amounts of time and is not a child's brick castle where it's easy to build a castle from nothing.

Acknowledge the efforts that was put forth even rather than support copy-pasting even.

**Comment by hipexscape** [comment]
It was just a test commit 

It isn't gonna to be merged so please ignore

**Comment by ossilator** [comment]
@StudioKeys when a commit is so unoriginal that i cannot say with _any_ confidence that it was copied, then i don't feel anything about it. i might mention that i have the same in my tree.

@hipexscape please don't do "tests" on a production system.

**Comment by amritokun** [comment]
🍿

**Comment by hipexscape** [comment]
Please don't take this matter any further 

I have already solved it with @shutter-cat.

**Comment by StudioKeys** [comment]
> @StudioKeys when a commit is so unoriginal that i cannot say with _any_ confidence that it was copied, then i don't feel anything about it. i might mention that i have the same in my tree.
> 
> @hipexscape please don't do "tests" on a production system.

How is it unoriginal now? Could you provide some context on that now?


Also see the commit dates 2023 is about two years ago now, not yesterday or day before. Also that's a commit from Android 13 which is 2 versions prior, so how is that unoriginal?

Explain yourself a bit.

Also testing commits on a large production repo is never a good thing and I agree with @ossilator on that.
Production systems shouldn't have test commits

**Comment by tanvirr007** [comment]
🧐

**Comment by amritokun** [comment]
Good Question, I am waiting for response!

**Comment by Sanjivns** [comment]
gang is here

**Comment by tanvirr007** [comment]
nah I'd win

**Comment by amritokun** [comment]
👀

**Comment by gwolf2u** [comment]
Child's play 
Not sure why create drama
But guess we like 🍿

**Pull request closed without merging**
