### PR TITLE
Add new themed icons

### PR DESCRIPTION
**Pull request by PycmShoma**
Added new themed icons and edited old files. Standartizaion and removed conditional links in code

### CODE REVIEW

**Comment by neobuddy89** [comment]
what's source for these icons?

**Comment by PycmShoma** [comment]
> 
Something from SuchiLauncher, something my friend drew, something converted through online services to svg and then to xml

**Comment by PycmShoma** [comment]
Something taken from target applications

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/dc07e105260e4ddf359593c833366a7ca1c9991b

**Pull request closed without merging**
